{
  "extends": ['stylelint-config-standard', 'stylelint-config-prettier'],
  "rules": {
    "rule-empty-line-before": ["always", {
    "except": ["after-single-line-comment"]}],
    "max-empty-lines": 2,
  }
}